/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CalendarFooter: typeof import('./src/components/CalendarFooter.vue')['default']
    CalendarGrid: typeof import('./src/components/CalendarGrid.vue')['default']
    CalendarHeader: typeof import('./src/components/CalendarHeader.vue')['default']
    CreateEventModal: typeof import('./src/components/CreateEventModal.vue')['default']
    EventCard: typeof import('./src/components/EventCard.vue')['default']
  }
}
